### ISSUE TITLE
Pas de son du Rs-ding sur les loc non Kvb, avec le script : OpenRails_Scripts-0.19.7

### ISSUE THREAD

**Issue by olivier97106** [Sharpe49/OpenRails_Scripts#1]
This is a log file for Open Rails. Please include this file in bug reports.
--------------------------------------------------------------------------------
Date/time  = 08/11/2020 14:46:42 (2020-11-08 13:46:42Z)
BIOS       = 2603 (American Megatrends Inc.)
Processor  = AMD FX(tm)-8350 Eight-Core Processor            (8 threads, 4 cores, 4,0 GHz) (L1-Cache 384 KB) (L2-Cache 8192 KB) (L3-Cache 8192 KB)
Memory     = 15,9 GB
Video      = NVIDIA GeForce GTX 770 (2,0 GB RAM) (nvlddmkm 27.21.14.5671)
Display    = \\.\DISPLAY1 (1920 x 1080, 32-bit, primary, 0 x 0)
Sound      = NVIDIA High Definition Audio (nvhda64v 1.3.38.35)
Sound      = Périphérique audio USB (usbaudio 10.0.19041.388)
Sound      = NVIDIA Virtual Audio Device (Wave Extensible) (WDM) (nvvad64v 4.13.0.0)
Sound      = Realtek High Definition Audio (rtkvhd64 6.0.1.7848)
Disk       = C: (Disque monté local, NTFS, 154,6 GB, 61,3 GB free)
Disk       = D: (Disque monté local, NTFS, 776,1 GB, 269,0 GB free)
Disk       = E: (Disque monté local, FAT32, 745,1 GB, 700,4 GB free)
Disk       = F: (Disque monté local, NTFS, 1117,8 GB, 614,2 GB free)
Disk       = G: (Disque monté local, NTFS, 1863,0 GB, 1089,8 GB free)
Disk       = H: (Disque monté local, NTFS, 1364,3 GB, 1004,5 GB free)
Disk       = I: (Disque CD-ROM, )
Disk       = J: (Disque monté local, NTFS, 1430,1 GB, 1296,9 GB free)
Disk       = N: (Disque amovible, )
Disk       = O: (Disque amovible, )
Disk       = P: (Disque amovible, )
Disk       = Q: (Disque amovible, )
Disk       = U: (Connexion réseau, NTFS, 698,6 GB, 391,8 GB free)
Disk       = W: (Connexion réseau, NTFS, 1829,4 GB, 1544,7 GB free)
Disk       = X: (Connexion réseau, NTFS, 1829,4 GB, 1544,7 GB free)
Disk       = Y: (Connexion réseau, NTFS, 1829,4 GB, 1544,7 GB free)
OS         = Microsoft Windows 10 Professionnel 64 bits (10.0.19042)
Runtimes   = 2.0.50727 SP2  3.0 SP2  3.5 SP1  4 Client  4 Full  4.0 Client 
Runtime    = 4.0.30319.42000 (32bit)
\\.\DISPLAY1 = NVIDIA GeForce GTX 770 (nvldumd.dll 27.21.14.5671)
    Anisotropy     = 16
    Render Targets = 4
    Streams        = 16 (stride 255)
    Textures       = 8 (16384 x 16384, repeat 8192, ratio 16384)
    Points         = 8192^2
    Volumes        = 2048^3
    Primitives     = 16777215
    Vertexes       = 16777215
    Vertex Shader  = 3.0 (4096 slots, 256 constants)
    Pixel Shader   = 3.0 (4096 slots)
    Clip Planes    = 8
--------------------------------------------------------------------------------
Version    = X1.3.1-124-g5037f814
Build      = 0.0.7398.33198 (2020-04-03 18:26:36Z)
Logfile    = C:\Users\olivi\Desktop\OpenRailsLog.txt
Executable = RunActivityLAA.exe
Argument   = -start
Argument   = -explorer
Argument   = D:\ORTS\ROUTES\RAILS DE FRANCE 3\PATHS\5427_player.pat
Argument   = D:\ORTS\TRAINS\CONSISTS\BB22200 15Kv.con
Argument   = 12:00
Argument   = 1
Argument   = 0
--------------------------------------------------------------------------------
ActRandomizationLevel          =                0
ActWeatherRandomizationLevel   =                0
AdhesionFactor                 =                130
AdhesionFactorChange           =                10
AdhesionMovingAverageFilterSize =                10
AdhesionProportionalToWeather  =                False
Alerter                        =                False
AlerterDisableExternal         =                True
Autopilot                      =                False
AuxActionEnabled               =                False
AvatarURL                      =                http://openrails.org/images/support-logos.jpg
BrakePipeChargingRate          =                21
BreakCouplers                  =                False
Cab2DStretch                   =                0
CarVibratingLevel              = (user set)     1
CircularSpeedGauge             = (user set)     True
ConditionalLoadOfDayOrNightTextures = (user set)     True
CorrectQuestionableBrakingParams =                False
CurveResistanceDependent       = (user set)     True
CurveSpeedDependent            =                False
DataLogger                     =                False
DataLoggerSeparator            =                comma
DataLogMisc                    =                False
DataLogPerformance             =                True
DataLogPhysics                 =                False
DataLogSpeedUnits              =                route
DataLogStart                   =                False
DataLogStationStops            =                False
DataLogSteamPerformance        =                False
DataLogTrainSpeed              =                False
DataLogTSContents              =                1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
DataLogTSInterval              =                10
DayAmbientLight                =                20
DebriefActivityEval            =                False
DebriefEvalFilename            =                OR-DebriefEval.txt
DebriefTTActivityEval          =                False
DisableTCSScripts              =                False
DistantMountains               =                True
DistantMountainsViewingDistance =                40000
DoubleWire                     =                False
DynamicShadows                 = (user set)     True
ExtendedAIShunting             = (user set)     True
ExternalSoundPassThruPercent   =                50
FastFullScreenAltTab           =                False
FullScreen                     =                False
GraduatedRelease               =                False
HotStart                       =                True
Language                       =                
LODBias                        =                0
LODViewingExtention            = (user set)     True
Logging                        =                True
LoggingFilename                =                OpenRailsLog.txt
LoggingPath                    =                C:\Users\olivi\Desktop
Menu_Selection                 = (user set)     D:\ORTS, D:\ORTS\ROUTES\RAILS DE FRANCE 3, , D:\ORTS\TRAINS\TRAINSET\SNCF_BB22200_ORTS_VL\SNCF_BB22201_15kV_Ex1_ORTS_VL.eng, D:\ORTS\TRAINS\CONSISTS\BB22200 15Kv.con, D:\ORTS\ROUTES\RAILS DE FRANCE 3\PATHS\5427_player.pat, 12:00, 1, 0
ModelInstancing                = (user set)     True
MSTSBINSound                   =                True
Multiplayer                    =                False
Multiplayer_Host               = (user set)     192.168.1.1
Multiplayer_Port               =                30000
Multiplayer_UpdateInterval     =                10
Multiplayer_User               = (user set)     olivier
MultiplayerClient              =                False
MultiplayerServer              =                False
NoForcedRedAtStationStops      =                False
OpenDoorsInAITrains            = (user set)     True
OverrideNonElectrifiedRoutes   =                False
PerformanceTuner               =                False
PerformanceTunerTarget         = (user set)     30
PrecipitationBoxHeight         =                100
PrecipitationBoxLength         =                500
PrecipitationBoxWidth          =                500
PreferDDSTexture               = (user set)     True
PressureUnit                   =                Automatic
Profiling                      =                False
ProfilingFrameCount            =                0
ProfilingTime                  =                0
ReplayPauseBeforeEnd           =                True
ReplayPauseBeforeEndS          =                0
RetainersOnAllCars             =                False
ScreenshotPath                 =                D:\Mes images\Open Rails
ShaderModel                    =                3
ShadowAllShapes                = (user set)     True
ShadowMapBlur                  =                True
ShadowMapCount                 =                4
ShadowMapDistance              =                1000
ShadowMapResolution            =                1024
ShowAvatar                     =                False
ShowErrorDialogs               =                True
SignalLightGlow                =                False
SoundDetailLevel               =                5
SoundVolumePercent             =                100
SpeedControl                   =                True
SuperElevationGauge            =                1435
SuperElevationMinLen           =                50
SuppressConfirmations          =                False
SuppressShapeWarnings          =                True
TTCreateTrainOnPoolUnderflow   =                True
TTOutputTimetableFullEvaluation =                False
TTOutputTimetableTrainInfo     =                False
TTUseRestartDelays             =                True
TunnelResistanceDependent      =                False
Units                          =                Automatic
UseAdvancedAdhesion            =                True
UseLargeAddressAware           =                True
UseLocationPassingPaths        =                False
UseMSTSEnv                     =                False
UseSuperElevation              = (user set)     1
VerticalSync                   = (user set)     True
ViewDispatcher                 = (user set)     True
ViewingDistance                =                2000
ViewingFOV                     =                45
WindowGlass                    = (user set)     True
WindowPosition_Activity        =                50, 50
WindowPosition_CarOperations   =                50, 50
WindowPosition_Compass         =                50, 0
WindowPosition_ComposeMessage  =                50, 50
WindowPosition_DriverAid       =                100, 100
WindowPosition_Help            =                50, 50
WindowPosition_NextStation     =                0, 100
WindowPosition_Quit            =                50, 50
WindowPosition_Switch          = (user set)     0, 52
WindowPosition_TrackMonitor    = (user set)     100, 1
WindowPosition_TrainList       = (user set)     97, 0
WindowPosition_TrainOperations = (user set)     51, 50
WindowSize                     =                1024x768
WindResistanceDependent        =                False
Wire                           =                True
WorldObjectDensity             =                10
YoungestFailedToRestore        =                0
--------------------------------------------------------------------------------
Mode       = explorer

Warning: Reading an item started with a double-quote character and followed by the + operator but then the next item must also be double-quoted. in D:\ORTS\ROUTES\RAILS DE FRANCE 3\RAILS DE FRANCE 3.trk:line 8

Route      = RAILS DE FRANCE 3
Path       = 5427_player (D:\ORTS\ROUTES\RAILS DE FRANCE 3\PATHS\5427_player.pat)
Consist    = BB22200 15Kv (D:\ORTS\TRAINS\CONSISTS\BB22200 15Kv.con)
Time       = 12:00:00 (12:00)
Season     = Summer (1)
Weather    = Clear (0)
--------------------------------------------------------------------------------
Loading  TRK

Warning: Reading an item started with a double-quote character and followed by the + operator but then the next item must also be double-quoted. in D:\ORTS\ROUTES\RAILS DE FRANCE 3\RAILS DE FRANCE 3.trk:line 8

 TDB

Warning: Track node 1133 pin 0 has invalid link to track node 0 in D:\ORTS\ROUTES\RAILS DE FRANCE 3\RAILS DE FRANCE 3.tdb:line 13180

Warning: Track node 1338 pin 0 has invalid link to track node 0 in D:\ORTS\ROUTES\RAILS DE FRANCE 3\RAILS DE FRANCE 3.tdb:line 15296

Warning: Track node 1937 pin 0 has invalid link to track node 0 in D:\ORTS\ROUTES\RAILS DE FRANCE 3\RAILS DE FRANCE 3.tdb:line 21077

Warning: Track node 1938 pin 0 has invalid link to track node 0 in D:\ORTS\ROUTES\RAILS DE FRANCE 3\RAILS DE FRANCE 3.tdb:line 21084

Warning: Track node 1950 pin 0 has invalid link to track node 0 in D:\ORTS\ROUTES\RAILS DE FRANCE 3\RAILS DE FRANCE 3.tdb:line 21352

Warning: Track node 1951 pin 0 has invalid link to track node 0 in D:\ORTS\ROUTES\RAILS DE FRANCE 3\RAILS DE FRANCE 3.tdb:line 21359

Warning: Track node 2325 pin 0 has invalid link to track node 0 in D:\ORTS\ROUTES\RAILS DE FRANCE 3\RAILS DE FRANCE 3.tdb:line 26173

 SIGCFG

Warning: Skipped extra SignalAspect in D:\ORTS\ROUTES\RAILS DE FRANCE 3\sigcfg.dat:line 10831

Warning: Skipped duplicate SignalShape FR_F-CARRRVL2.S in D:\ORTS\ROUTES\RAILS DE FRANCE 3\sigcfg.dat:line 12834

Warning: 1 missing SignalShape(s) in D:\ORTS\ROUTES\RAILS DE FRANCE 3\sigcfg.dat:line 14278

 DAT ACT RDB

Warning: Track node 3220 pin 0 has invalid link to track node 0 in D:\ORTS\ROUTES\RAILS DE FRANCE 3\RAILS DE FRANCE 3.rdb:line 27087

Warning: Track node 3237 pin 0 has invalid link to track node 0 in D:\ORTS\ROUTES\RAILS DE FRANCE 3\RAILS DE FRANCE 3.rdb:line 27210

Warning: Track node 3240 pin 0 has invalid link to track node 0 in D:\ORTS\ROUTES\RAILS DE FRANCE 3\RAILS DE FRANCE 3.rdb:line 27233

Warning: Track node 4522 pin 0 has invalid link to track node 0 in D:\ORTS\ROUTES\RAILS DE FRANCE 3\RAILS DE FRANCE 3.rdb:line 37943

 CARSPAWN SIGSCR ssssssWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW

Warning: Incomplete crossover : indices 2493 and 2448

Warning: Ignored invalid track node 1133 pin [0,0] link to track node 0

Warning: Ignored invalid track node 1338 pin [0,0] link to track node 0

Warning: Ignored invalid track node 1937 pin [0,0] link to track node 0

Warning: Ignored invalid track node 1938 pin [0,0] link to track node 0

Warning: Ignored invalid track node 1950 pin [0,0] link to track node 0

Warning: Ignored invalid track node 1951 pin [0,0] link to track node 0

Warning: Ignored invalid track node 2325 pin [0,0] link to track node 0

 TURNTBL

Warning: Skipped script d:\orts\trains\trainset\sncf_bb22200_orts_vl\script\old_tcs_france.cs with error:
   Le type ou le nom d'espace de noms 'Blinker' est introuvable (une directive using ou une référence d'assembly est-elle manquante ?), line: 89, column: 9

 ENV SIGCFG SIGCFG

Warning: Skipped extra SignalAspect in D:\ORTS\ROUTES\RAILS DE FRANCE 3\sigcfg.dat:line 10831

Warning: Skipped duplicate SignalShape FR_F-CARRRVL2.S in D:\ORTS\ROUTES\RAILS DE FRANCE 3\sigcfg.dat:line 12834

Warning: 1 missing SignalShape(s) in D:\ORTS\ROUTES\RAILS DE FRANCE 3\sigcfg.dat:line 14278

 TTYPE

Information: Allocation for 87 500 particles:

     14 000 000 B RAM vertex data
      2 100 000 B RAM index data (temporary)
     14 000 000 B VRAM DynamicVertexBuffer
      2 100 000 B VRAM IndexBuffer

TTTTTTTTTWWWSSSSSSSSSSSSSSSSSSSSSS TRP(default)SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS$WSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Warning: w-006091+014624.w scenery object 7338 with StaticFlags 00000000 references non-existent D:\ORTS\ROUTES\RAILS DE FRANCE 3\Shapes\FR_Im_PLM_1.s

Warning: w-006091+014624.w scenery object 7339 with StaticFlags 00000000 references non-existent D:\ORTS\ROUTES\RAILS DE FRANCE 3\Shapes\FR_Im_PLM_1.s

Warning: w-006091+014624.w scenery object 7340 with StaticFlags 00000000 references non-existent D:\ORTS\ROUTES\RAILS DE FRANCE 3\Shapes\FR_Im_PLM_1.s

$WSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSWWWCS

Information: Game.ReplaceState(GameStateViewer3D)  GameStateViewer3D

Loader: Time       = 00:01:14.0481568 ms
Loader: Expected   = 360 071 942 bytes
Loader: Actual     = 360 064 232 bytes
Loader: Difference = -7 710 bytes (0,0 %)

Information: Ignored missing animations data in shape d:\orts\routes\rails de france 3\shapes\mr_1383.s

SSSSSSSSSSSSSSSSSSSSSSSSSSS

Warning: File mp_rail_low1.wav missing from D:\ORTS\SOUND

Warning: File x_mp_rail_low1.wav missing from D:\ORTS\SOUND

SSS

Warning: Missing texture d:\orts\routes\rails de france 3\textures\.ace replaced with default texture

Warning: File mp_joint1.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint12.wav missing from D:\ORTS\SOUND

SSS

Warning: File mp_joint3.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint12.wav missing from D:\ORTS\SOUND

S

Warning: File x_mp_joint10.wav missing from D:\ORTS\SOUND

Warning: File mp_joint3.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint1.wav missing from D:\ORTS\SOUND

Warning: File mp_joint8.wav missing from D:\ORTS\SOUND

S

Warning: File x_mp_joint11.wav missing from D:\ORTS\SOUND

Warning: File mp_joint5.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint1.wav missing from D:\ORTS\SOUND

Warning: File mp_joint8.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint5.wav missing from D:\ORTS\SOUND

Warning: File mp_joint8.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint4.wav missing from D:\ORTS\SOUND

Warning: File mp_joint1.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint9.wav missing from D:\ORTS\SOUND

Warning: File mp_joint10.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint4.wav missing from D:\ORTS\SOUND

Warning: File mp_joint10.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint2.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint3.wav missing from D:\ORTS\SOUND

Warning: File mp_joint5.wav missing from D:\ORTS\SOUND

Warning: File mp_joint12.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint11.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint10.wav missing from D:\ORTS\SOUND

Warning: File mp_joint7.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint8.wav missing from D:\ORTS\SOUND

Warning: File mp_joint6.wav missing from D:\ORTS\SOUND

Warning: File mp_joint1.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint5.wav missing from D:\ORTS\SOUND

Warning: File mp_joint3.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint11.wav missing from D:\ORTS\SOUND

Warning: File mp_joint6.wav missing from D:\ORTS\SOUND

Warning: File x_mp_joint12.wav missing from D:\ORTS\SOUND

TTTWSSWSSSS

Warning: File mp_joint6.wav missing from D:\ORTS\SOUND

SSSSSSSSSSSSSSSSS

Warning: File x_mp_joint8.wav missing from D:\ORTS\SOUND

SSSSSSSS

Warning: File mp_joint8.wav missing from D:\ORTS\SOUND

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Information: Game.PopState()  

SS

**Comment by Sharpe49** [comment]
Euh, la prochaine fois met le fichier en pièce jointe (glisser le fichier dans la fenêtre de texte). Cela sera plus pratique et plus lisible. ;)

Au niveau du problème, ici, le script n'a pas réussi à charger une fonctionnalité incluse dans le simulateur. En effet, la version X1.3.1-124 ne l'a pas. Il faut mettre à jour vers la version de test en passant par le menu Options => Mise à jour.

**Comment by Sharpe49** [comment]
Pas de retour depuis le dernier message, je ferme.
