### ISSUE TITLE
FU KVB sur RR40 signal Suisse

### ISSUE THREAD

**Issue by ptitduplex** [Sharpe49/OpenRails_Scripts#3]
A l'arrivée en gare de Bâle SNCF (LGE v4), FU KVB au passage de l'équivalent Suisse d'un RR40.
Le signal a été passé à 30km/h et acquitté immédiatement.

Le signal utilise un grand nombre de "signal head",  qui semble être utilisées pour l'avertissement et le rappel 40, cela ne métonnerait pas que l'une de ces têtes donne l'information "STOP". Je n'ai aucune idée de comment le script gère les têtes multiples.

**Comment by Sharpe49** [comment]
Ok, donc pour reproduire le test, il faut que je fasse Mulhouse - Bâle ?

**Comment by ptitduplex** [comment]
C'est ca. J'ai utilisé le chemin livrée avec la route, avec une arrivée voie 1 (voie de droite) en gare de Bâle SNCF pour la voie 31. Le signal incriminé est le dernier signal avant l'entrée en gare. C'est celui qui protège l'aiguille n°13594

**Comment by Sharpe49** [comment]
Ok, il y avait un bug car le signal suisse est fait de manière différente aux signaux français. C'est désormais corrigé dans la version 0.19.9.
[https://github.com/Sharpe49/OpenRails_Scripts/releases/tag/v0.19.9](https://github.com/Sharpe49/OpenRails_Scripts/releases/tag/v0.19.9)

**Comment by ptitduplex** [comment]
D'accord. Merci pour ton retour et bon courage pour la suite du développement !
